--- 
apiVersion: spec.keptn.sh/0.2.3
kind: Shipyard
metadata: 
  name: shipyard-log-forwarding
spec: 
  stages: 
    - 
      name: dev
      sequences: 
        - 
          name: evaluation
          tasks: 
            - name: evaluation
              properties: 
                timeframe: "invalid"